---
Title: "Logboek - Vani"
Autheur: "Vani Rembet"
Output: html_document
---

# INTRODUCTIE
Wij doen een onderzoek naar de Duitse taalvaardigheid in Nederland. Het doel van dit onderzoek is het gemiddelde taalniveau volgens het CEFR voor Duits onder Nederlanders te bepalen. 

## Onderzoeksvraag
In hoeverre verschilt de Duitse taalvaardigheid tussen Nederlandse volwassenen van 40 jaar en ouder en jongere volwassenen (18–39 jaar)? 

## Hypothese
Het gemiddelde niveau onder jongeren is A2 en B2 is zeer hoog. Het gemiddelde niveau onder 40-plussers is B1 en C1+ zijn extreem hoge niveaus. 

## Gebruikte data
- Leeftijdsgroepen 
- Locatie
- Onderwijsniveau
- Gebruik aan Duitse taal
- Hoe belangrijk is de Duitse taal

- Behaalde niveau op basis van de taaltoets (!!!)


# LOGBOEK

---
Datum: "20-05-2026"

# Doel van de dag
- Logboek maken
- Kijken of wij kunnen beginnen met onze vragenlijstresultaat kunnen toepassen in R
- Werken aan de Journal Club

# Motivatie
- Wij krijgen als opdracht om een logboek te maken en het elke dag bij te houden
- Wij hebben inmiddels al genoeg gegevens verzameld door onze vragenlijst aan deelnemers te laten maken
- Journal Club moet voor 24/05 al af zijn

# Wat heb ik gedaan?
- Logboek gemaakt
- Presentatie gemaakt voor Journal Club
---

---
Datum: "21-05-2026"

# Doel van de dag
- R-code dat Jesse heeft gemaakt even goed schoonmaken
- Werken aan de Journal Club

# Motivatie
- R moet deze week af zijn volgens de planning in PvA

# Wat heb ik gedaan?
- R-code van Jesse verbeterd (zie git)
- Verder met de Journal Club
---

---
Datum: "22-05-2026"

# Doel van de dag
- R-code verbeteren
- Andere grafieken maken voor andere deelvragen in onze R-code
- Laatste dingen voor Journal Club afmaken en eventueel inleveren
- Elkaars Git beoordelen

# Motivatie
- We hebben een grafiek gemaakt voor een gemiddelde niveau van alle deelnemers, maar nog niet op basis van 1 persoon
- Taak gekregen om elkaars Git te beoordelen
- Journal Club graag voor mezelf voor het weekend afmaken zodat weekend alleen hoeft te oefenen

# Wat heb ik gedaan?
- Een aangepaste grafiek gemaakt waarmee je ziet wat voor niveau per persoon heeft gehaald op basis van de hoeveel gehaalde vragen per niveau.
- Een drempel toegevoegd in de code om niveau makkelijker te bepalen
- Verder met de Journal Club gewerkt. Het is nog steeds niet af :(
---

---
Datum: "25-05-2026"

# Doel van de dag
- R-code verbeteren
- Laatste dingen voor Journal Club afmaken en eventueel inleveren
- Eventueel andere grafieken maken voor andere deelvragen in R

# Motivatie
- Van Jesse en Dennis een probleem gekregen over mijn R-code dat gefixt moet
- Journal Club moet echt af zijn voor 26/05
- Mocht ik nog tijd heb, dan misschien alvast beginnen met het maken van andere grafieken

# Wat heb ik gedaan?
- Probleem van mijn R-code gefixt: scores_per_persoon was niet gedefinieerd, maar nu wel.
- 
---
