---
title: "logboek_jesse"
author: "Jesse Postma"
date: '`r Sys.Date()`'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Logboek Jesse Postma \| Wetenschappelijke Cyclus 2026

## Introductie

De Duitse taalbeheersing onder Nederlanders neemt af, met een daling in eindexamens Duits van circa 68.000 in 2018 naar 49.000 in 2025 (−23%). Ook in het hoger onderwijs is een vergelijkbare terugloop zichtbaar. Mogelijke oorzaken zijn een curriculum dat vooral focust op technische taalvaardigheden, ten koste van motivatie en culturele context. Dit onderzoek bekijkt hoe goed Nederlanders Duits beheersen en welke factoren daarbij een rol spelen, met focus op leeftijd, opleidingsniveau en woonlocatie (grensregio vs. Randstad). Verwacht wordt dat oudere generaties, hoger opgeleiden en inwoners van grensregio’s beter scoren. Hiervoor wordt een kwantitatieve studie uitgevoerd met een CEFR-gebaseerde taaltoets en een achtergrondvragenlijst, waarna de resultaten per groep worden vergeleken.

### 20/05/26

Start logboek, we hebben voor vandaag afgesproken voor de kopjes introductie, methoden en materialen een eerste versie af te maken. We gaan vandaag individueel ontdekken wat voor figuren we willen genereren met R.

Ik heb de taak op mij genomen om het excel bestand wat uit de Forms kwam op te schonen aangezien daar niet gemakkelijk juiste/onjuiste antwoorden uit kwamen helaas. Dit hield in dat ik alle antwoorden in een aparte regel zet en daar de antwoorden van de respondents mee vergelijk in een aparte sheet en de rest van de form overneem in de resultaatsheet. Ik heb voor de formules ChatGPT gebruikt:

`{=--(TRIM(LOWER(Sheet1!Q4))=TRIM(LOWER(Sheet1!Q$1)))}`

### 21/05/26

Ik was vandaag iets te laat bij de workshop schrijven van Dave, gelukkig denk ik dat ik wel prima schrijf. Dus maar zelfstandig bezig. Ik heb het logistic regression voorbeeld wat Emile gister op brightspace had gedeeld gedownload, en probeer nu het model toe te passen op ons dataset. Daarvoor heb ik een testbestandje gemaakt in de repo waarin ik de csv inlaad en daar wat mee ga prutsen.

Het wil allemaal niet echt, het voorbeeld is erg specifiek en onze data is heel anders. Ik heb eerst onze kolomnamen veranderd naar kortere namen aangezien daar hele vragen in stonden.

Daarna heb ik de df gepivot met tidyr zodat de vragen en antwoorden er apart in stonden. Daarna heb ik chatgpt geraadpleegd omdat ik het lastig vond het voorbeeld toe te passen op onze data. Uiteindelijk wel een mooi model en grafiekje erbij.

### 22/05/26

Vandaag 8:30 begonnen, Dave was daar blij mee. Ik realiseerde mij gister nog dat het logistic model wat ik gister had uitgewerkt alleen op het totaalplaatje slaat. Dus het vertelt alleen hoe moeilijk elke vraag bevonden is (kans op goed hebben). Dit geeft geen info over het niveau van een individu zelf, dus ik wil graag vandaag proberen om dat te gaan doen en om dan ook onze data aan te passen met nieuwe kolommen voor het niveau/score (2 zodat we een catagorische niveau hebben en een numerische score).

Het is inmiddels gelukt, ik met wat hulp van NotebookLM Item Response Theory geimplementeerd met de library MIRT. Item Response Theory is een model wat vaak wordt gebruikt in educatie en psychologie en geeft per persoon een score die gemakkelijk kan worden omgezet naar CEFR.

Vani heeft ook geprobeerd dit te tackelen en heeft een mooie visuele representatie van de niveaus, in combinatie is dit erg handig denk ik dus we beide implementaties houden voor nu.

Ik heb nog thresholding toegevoegd aan de scoring, nu moet iemand 60 % goed hebben. Vani en mijn approaches verschillen nog wel wat. Dus dat proberen we te verhelpen, maar ik weet niet waar het probleem nu nog moet liggen - zeker niet met de nieuwe thresholding:

```{bash}
prob_target <- 0.60
logit_add <- log(prob_target / (1 - prob_target))

            ...
            score < threshold_A2 ~ "A1",
            score >= threshold_A2 & score < threshold_B1 ~ "A2",
            score >= threshold_B1 & score < threshold_B2 ~ "B1",
            score >= threshold_B2 & score < threshold_C1C2 ~ "B2",
            score >= threshold_C1C2 ~ "C1/C2",
            ...

```
