---
title: "logboek_Dennis"
output: html_document
date: "2026-05-20"
---

## R Markdown
20-5-2026
Ik ga nu werken aan de introductie van onze paper. Ik ga eerst kijken welke relevante informatie ik kan vinden in onze literatuur over de motivatie en het niveau van jongeren aangaande de Duitse taal.Nu voeg ik een nieuw artikel toe aan onze literatuurlijst. Het artikel is van de Radboud Universiteit en het legt uit wat de officiële taalniveaus zijn volgens de CEFR-taalniveaus. Dit artikel voeg ik toe, omdat ik in de introductie wil uitleggen welke officiële niveaus van de Duitse taal worden erkend en dat moet ik met literatuur kunnen onderbouwen.

22-5-2026
Ik ga werken aan mijn presentatie van de journalclub en mijn artikel lezen.

25-5-2026
Ik ga mijn artikel lezen en als ik iets niet begrijp ga ik het opzoeken.
Ik ga kijken of ik de logistische regresse van Vani kan gebruiken om de niveaus van mensen te bepalen en te visualiseren.

26-5-2026
Het doel van vandaag is om mijn presentatie voor de journalclub af te maken en in te leveren, omdat de presentatie morgen om 9:00 maximaal ingeleverd moet worden. Ik ga 
het artikel doorlezen en alle belangrijke termen en onderzoeksresultaten in de presentatie zetten. Verder ga ik afbeeldingen van onderzoeksresultaten in de presentatie zetten. Dit doe ik, omdat de powerpoint dan overzichtelijk de belangrijkste termen en resultaten laat zien, zodat ik ze als steekwoorden kan gebruiken. Ik ga ook een plaatje toevoegen aan de eerste dia om de eerste dia mooier te maken. Ik heb het artikel doorgelezen en de belangrijkste onderzoeksresultaten als steekwoorden in de presentatie gezet. Hiervoor heb ik het gedeelte 'results and discussion' van het artikel geraadpleegd. Deze steekwoorden zijn: Krokodillen zijn geen ‘levende fossielen’, Externe factoren spelen een cruciale rol in de evolutie van pseudosuchia, Vrijwel geen bewijs voor Cope’s rule en Geen geleidelijke evolutie. Deze steekwoorden heb ik in de presentatie gezet, zodat ik de in de powerpoint kan aflezen welke onderwerpen ik moet behandelen tijdens de presentatie, gezien het feit dat ik niet het hele artikel kan uitleggen in 15 minuten. Verder bevat het gedeelte 'results and discussion' van het onderzoek een aantal afbeeldingen. Deze afbeeldingen heb ik ook toegevoegd aan de presentatie, omdat deze afbeeldingen belangrijke onderzoeksresultaten weergeven, namelijk een fylogenetische boom en het evolutionaire verloop van pseudosuchia. Bij de dia 'materiaal en methoden' heb ik in het artikel het gedeelte 'methods' doorgelezen. Ik heb de computerprogramma's en methoden die de onderzoekers voor hun onderzoek hebben gebruikt in de presentatie als steekwoorden in de presentatie gezet. Deze steekwoorden zijn: Peer-reviewed artikelen met afbeedingen van fossielen Gemeten m.b.v ImageJ, iterative imputation m.b.v PAST versie 3.1 voor Mac OS, phylogenetic comparative methods (PCM), BayesTraits versie 2 en ACE functie in de APE package in R. Ook dit heb ik gedaan zodat ik van de powerpoint kan aflezen welke onderwerpen ik moet aankaarten tijdens de presentatie, aangezien ik niet het hele artikel in 15 minuten kan uitleggen.
 
27-5-2026
Ik heb de powerpoint ingeleverd.
Het doel van vandaag is om beter voorbereid te zijn op de presentatie van de journalclub op 29 mei 2026. Ik heb inmiddels de onderwerpen die ik ga aankaarten in de powerpoint gezet als steekwoorden en als afbeeldingen. Deze onderwerpen ga ik één voor één bij langs. Als ik iets niet kan uitleggen, ga ik het onderwerp opzoeken in het artikel om te kijken of het daar uitgelegd wordt. Zo niet, dan ga ik het onderwerp opzoeken in google. Ook ga ik vantevoren een aantal vragen bedenken die gesteld kunnen worden na de presentatie zodat ik die vragen kan beantwoorden. Ik kies voor deze werkwijze, omdat ik dan alle onderwerpen die ik het meest belangrijk vind om te vertellen goed kan uitleggen. Ik heb als eerste opgezocht wat ImageJ precies is via google. Ik heb deze zoekopdracht in google: 'ImageJ'. Vervolgens heb ik via wikipedia informatie gekregen over ImageJ: https://en.wikipedia.org/wiki/ImageJ.
Ik heb nu op google gezocht naar de betekenis van iterative imputation. Mijn zoekopdracht was: 'iterative imputation', waarna ik de volgende website gebruikte om informatie uit te halen: https://machinelearningmastery.com/iterative-imputation-for-missing-values-in-machine-learning/
Ik heb deze zoekopdracht gebruikt in google: 'PAST software' om informatie over het programma PAST te zoeken. Ik heb deze website gebruikt als informatiebron: https://palaeo-electronica.org/2001_1/past/pastprog/index.html.

Ik gebruik deze zoekopdracht in google om informatie over BayesTraits te krijgen: 'BayesTraits'. Ik gebruik deze website als informatiebron: https://www.evolution.reading.ac.uk/BayesTraitsV5.0.3/BayesTraitsV5.0.3.html.

Ik gebruik deze zoekopdracht in google om uit te zoeken wat de APE package in R is: 'APE package in R'. Ik gebruik deze website als informatiebron: https://academic.oup.com/bioinformatics/article/20/2/289/204981

Ik gebruik deze zoekopdracht om uit te zoeken wat de ACE functie in de APE package in R doet: 'APE package in R ACE function'. Ik gebruik deze site als informatiebron: https://www.rdocumentation.org/packages/ape/versions/5.8-1/topics/ace.

Vervolgstappen: ik ga morgen de belangrijke punten uit het artikel die in de powerpoint staan uit mijn hoofd leren en de presentatie oefenen.

2-6-2026
Het doel van vandaag is om de grafiek te maken die de hoogst behaalde opleiding uitzet tegen het niveau Duits van de deelnemers. Ik haal de data uit het bestand cleaned_scores.csv, omdat dit bestand alle benodigde informatie van de deelnemers bevat, inclusief de berekende niveaus van het Duits. Ik probeerde aanvankelijk een for-loop en een if-statement te gebruiken. Met deze methode wilde ik van elk schoolniveau de behaalde CEFR-niveaus eruit halen. Deze methode werkt echter niet. De betreffende code is terug te vinden in github in de volgende commit: 'for-loop en if-statement toegevoegd'. Deze methode werkt niet, omdat je niet met een for-loop bij een dataset kan gebruiken.Ik gebruik nu de functie tapply() om per opleidingsniveau het gemiddelde niveau Duits te bepalen. De code is terug te vinden in de commit 'gemiddelde niveau Duits per opleidingsniveau bepaald'. Ik gebruik deze functie, omdat ik daarmee het gemiddelde kan bepalen van getallen die gekoppeld zijn aan categorische data. Ik heb voor de niveaus van het Duits de kolom 'scores' gebruikt, omdat deze kolom getallen bevat die het niveau van deelnemers weergeven, dus daar kan ik het gemiddelde van berekenen. Voor de hoogstbehaalde opleidingsniveaus heb ik de kolom 'opleiding' gebruikt, omdat deze kolom van elke deelnemer het hoogstbehaalde opleidingsniveau weergeeft. Ik kies een staafdiagram om de data te visualiseren. Dat doe ik, omdat het hier om categorische data gaat en ik denk dat een staafdiagram goed geschikt is voor categorische data. Ik wil de hoogstbehaalde opleidingsniveaus op de x-as zetten en de gemiddelde niveaus van Duits op de y-as. Ik ga via google opzoeken hoe je een staafdiagram maakt in R. Ik gebruik deze zoekfunctie: 'staafdiagram in R maken'. Vervolgens ben ik deze website tegengekomen die ik als informatiebron gebruik: https://statlas.ugent.be/technieken/Data%20verkennen/datavisualisatie_base.html#4_Staafdiagram. Op deze bron staan een aantal demonstraties van het visualiseren van data met R. Ik heb een eerste poging gedaan om de staafdiagram te maken. Het is me nog niet gelukt. De code is terug te vinden in de volgende commit: 'staafdiagram maken poging 1'. Ik heb de code aangepast, maar ik krijg nog geen staafdiagram. In de commit 'staafdiagram maken poging 2' staat de nieuwe code. Het doel van vandaag is niet behaald. Tot nu toe heeft mijn werk alleen wat getallen opgeleverd die ik niet begrijp. De conclusie is dat mijn code nog niet goed is om een staafdiagram te maken. De volgende stap is om te zoeken naar andere manieren om mijn code te schrijven.

3-6-2026
Het doel van vandaag is om de barplot af te krijgen die het hoogstbehaalde opleidingsniveau uitzet tegen de niveaus van Duits. Ik zoek via google naar een methode om dit te doen met ggplot. Dit is mijn zoekopdracht: 'making barplot in R using ggplot'. Ik vond deze site voor informatie: https://r-graph-gallery.com/218-basic-barplots-with-ggplot2.html. Ik krijg momenteel een foutmelding als ik ggplot probeer te gebruiken. De code is terug te vinden in de volgende commit: 'eerste poging barplot maken met ggplot2()'. Ik heb via google gezocht naar de functies van geom_bar. Ik heb deze zoekopdracht gebruikt: 'geom_bar'. Ik heb deze site gevonden: https://ggplot2.tidyverse.org/reference/geom_bar.html. Ik heb op een andere manier geprobeerd ggplot te gebruiken, maar deze manier werkt ook niet. De code is terug te vinden in de commit: 'tweede poging barplot maken met ggplot2()'. Nu is het gelukt om de barplot te maken. De code is te vinden in de volgende commit: 'barplot opleidingsniveaus toegevoegd'. Ik heb nu de opleidingen op volgorde van laag naar hoog gezet en ik heb de balken kleuren gegeven. Ook heb ik de manier waarop ik de gemiddelde Duits niveaus per opleiding bereken verandert. De code voor deze veranderingen staan in deze commit: 'barplot opleidingen op volgorde van laag naar hoog gezet'. Ik heb de balken van de staafdiagram blauw gemaakt, de namen van de assen aangepast en een titel aan de staafdiagram toegevoegd. De code van deze verandering is terug te vinden in de volgende commit: 'titel toegevoegd, balken blauw gemaakt en namen assen aangepast'. Resultaten: ik heb de barplot van de opleidingsniveaus gemaakt. Volgens deze barplot is het niveau Duits van iemand die basisonderwijs als hoogste opleidingsniveau heeft laag. Mensen met vmbo als hoogste niveau hebben een vrij hoog Duits nivea en mensen met havo niveau hebben weer een veel lager Duits niveau. Mensen met vwo als hoogste niveau hebben een wat hoger niveau dan havo, maar nog steeds lager dan vmbo. Bij de mensen die een opleiding op de middelbare school als hoogste opleidingsniveau hebben gaat het niveau Duits dus niet per se omhoog naarmate het opleidingsniveau hoger wordt. Bij mensen die mbo, hbo en wo als hoogste opleiding hebben gaat het niveau Duits wel van laag naar hoog naarmate het opleidingsniveau hoger wordt. Wat verder opvalt is dat mensen met mbo en hbo als hoogste opleidingsniveau hebben een lager Duits niveau hebben dan de mensen die een opleiding op de middelbare school als hoogste opleidingsniveau hebben. Mensen die wo als hoogste opleidingsniveau hebben scoren hoger op Duits dan mensen met havo en vwo als hoogste niveau, maar scoren lager dan mensen met vmbo als hoogste opleidingsniveau. Op basis van deze resultaten kan geconcludeerd worden dat het Duits niveau niet automatisch hoger wordt naarmate mensen een hogere opleiding volgen.

4-6-2026
Het doel van vandaag is om de resterende grafieken te maken die ik volgens onze takenverdeling moet maken. Tot nu toe heb ik de volgende grafieken gemaakt: een staafdiagram dat de invloed van wonen of werken in Duitsland op het Duits niveau aangeeft, een staafdiagram dat de invloed op het hebben van een Duitse kennis of familielid op het Duits niveau aangeeft, een staafdiagram dat het gemiddelde niveau Duits uitzet tegenover hoevaak de deelnemrs Duits gebruiken in het dagelijks leven, een puntendiagram dat de individuele Duits niveaus toont op de y-as met de afstand met hoever de deelnemers wonen van de Duitse grens in km op de x-as en een staafdiagram die laat zien wat het gemiddelde Duits niveau is naarmate de deelnemers verder van de Duits grens wonen. Voor de staafdiagrammen heb ik dezelfde syntax of grotendeels dezelfde syntax gebruikt als bij mijn staafdiagram die de relatie tussen het Duits niveau en het hoogstbehaalde opleidingsniveau laat zien. Ik heb deze syntax hergebruikt, omdat mijn code voor het maken van een staafdiagram werkte bij de grafiek die de relatie tussen opleidingsniveau en Duits niveau laat zien. Voor de puntendiagram heb ik ggplot en geom_point() gebruikt. De syntax voor deze twee functies heb ik uit mijn aantekeningen gehaald die ik tijdens de colleges heb gemaakt. Ik heb aanvankelijk gekozen voor een puntendiagram om het verband tussen het Duits niveau en de afstand tot de Duitse grens te laten zien, omdat in Teams werd voorgesteld om een scatterplot te gebruiken. Uiteindelijk heb ik besloten om een staafdiagram te gebruiken, zodat ik de afstanden kan verdelen in categorieën van 100 km. Op de x-as staan de afstanden tot de Duitse grens per 100 km en op de y-as de gemiddelde niveaus Duits. Ik heb het puntendiagram niet verwijderd, omdat ik het handig vind dat ik nu twee grafieken heb, één alle individuele scores laat zien met hoe ver de deelnemers van de grens wonen en een andere grafiek die de gemiddelde Duits niveaus per 100 km laat zien. Voor het verdelen in van de afstand in categorieën van 100 km heb ik de functie cut() gebruikt. Ook deze functie heb ik uit mijn aantekeningen gehaald. Ik wilde een staafdiagram maken met de situaties waarin de deelnemers Duits gebruiken in hun dagelijks leven met het gemiddelde Duits niveau per situatie. De methode die ik gebruikte om het gemiddelde niveau per categorie te berekenen werkt echter niet, omdat de deelnemers bij deze vraag meerdere antwoorden konden aanvinken. Ik heb daarom eerst ervoor gezorgd dat de antwoorden die meerdere situaties hadden werden gesplitst. Wanneer een deelnemer bijvoorbeeld Duits gebruikt voor vakantie en werk, dan wordt het niveau van die persoon toegewezen aan zowel de categorie 'werk' als categorie 'vakantie'. Vervolgens heb ik de gemiddelde scores per situatie berekend en een staafdiagram gemaakt met de situaties waarin Duits wordt gebruikt op de x-as en de gemiddelde Duits scores op de y-as. Voor het splitsen van de antwoorden en het berekenen van het gemiddelde bij deze laatste grafiek heb ik met toestemming van Jesse een stuk van zijn code overgenomen. De code is terug te vinden in de volgende commit: 'barplot situaties toegevoegd'. De niveaus Duits in de grafieken staan nu nog in theta scores. De volgende stap is om de scores om te zetten naar CEFR-niveaus.

5-6-2026
Het doel van vandaag is om bij de grafieken ook de CEFR-scores te laten zien. Dit is gelukt, de code is te vinden in de volgende commit: 'CEFR-niveaus toegevoegd aan de grafieken in de paper'. Het lukte mij niet om de scores om te zetten naar CEFR-niveaus, dus ik heb Jesse om hulp gevraagd. De grafiek van de situaties toont nu de CEFR-niveaus. Ik gebruik de code voor deze grafiek nu ook bij de andere grafieken. De grafiek is nu echter niet heel leesbaar. De labels op de x-as staan te dicht bij elkaar waardoor ze niet goed leesbaar zijn. Jesse heeft mij een manier gegeven om de labes 45 graden te draaien zodat ze wel leesbaar zijn. Ik heb de titel van die situaties weergeeft veranderd. De titel was 'invloed hoe vaak mensen Duits' gebruiken op hun niveau. Dit heb ik aangepast, omdat deze titel bij de verkeerde grafiek hoorde. Ik krijg nu de foutmelding Error in get_level() : argument "score" is missing, with no default. Ik had get_levels() aangeroepn zonder argument en die heb ik nu verwijderd. Nu krijg ik een foutmelding in de barplot van wonen en werken in Duitsland. Ik krijg deze foutmelding: Problem while computing aesthetics.
ℹ Error occurred in the 1st layer.
Caused by error in `check_aesthetics()`:
! Aesthetics must be either length 1 or the same as the data
(2).
✖ Fix the following mappings: `fill`. Dit kwam, omdat ik de scores uit onze dataset heb gehaald, terwijl ik de berekende gemiddeldes moet gebruiken. CEFR-niveaus bij andere grafieken gezet. Ik heb de introductie gedeeltelijk verder geschreven. Ik heb ook een nieuwe informatiebron gevonden om te citeren in de introductie: 'https://duitslandinstituut.nl/naslagwerk/1223/feiten-en-cijfers'. Vervolgstappen: ik ga de introductie en de abstract afmaken.

6-6-2026
Het doel van vandaag is om de abstract en de introductie van onze paper af te maken. Hierbij gebruik ik de template van Michiel Noback, omdat ik deze template een goede leidraad vind om een paper te schrijven. Ik heb voor de introductie een nieuwe bron gevonden: https://www.rijksoverheid.nl/actueel/weblogs/bzers-wereldwijd/2024/waarom-kan-nederland-niet-zonder-internationale-handel. Dit is een artikel van de overheid dat uitlegt waarom internationale handel belangrijk is voor Nederland. Ik gebruik dit artikel als bron om te bewijzen dat Duitsland één van de grootste handelspartners van Nederland is. De abstract en introductie zijn geschreven. De volgende stap is om te controleren of er nog verbeterpunten zijn in onze paper.

9-6-2026
Het doel van vandaag is om de paper af te maken. Ik had gezien dat Jesse de introductie en abstract heeft veranderd. Ik heb vandaag met hem gekeken of de introductie en abstract nog goed zijn. Ik heb een aantal dingen weer veranderd. Ook heeft hij een aantal grafieken veranderd en een stukje van Vani's tekst veranderd. Ik vond dit verder geen probleem, maar ik vroeg wel of hij de volgende keer eerst met mij wil overleggen voordat hij mijn werk verandert. Ik wilde voor de zekerheid controleren of we de paper nog kunnen verbeteren. Ik heb daarom aan Ronald gevraagd of hij wil kijken of er nog verbeterpunten zijn in onze paper. Ik heb toen aantekeningen gemaakt in een Word-document. Dit zijn mijn aantekeningen: 'Je hoeft R-studio niet te noemen
Bij tabellen geef ze namen of nummers en een beschrijving wat ze doen. Verwijs in de tekst naar de tabellen. In een tabel moet de beschrijving boven staan, bij figuren eronder. 
Voeg titels toe aan grafieken. Beschrijving figuren mag uitgebreider. 

In de resultaten staan conclusie en discussie, die horen daar niet. Leg alle afkortingen uit. Leg bij de figuren uit wat je ziet. Tekst bij resultaten. Maak apart kopje voor discussie, gebruik referenties in de discussie. In introductie waarom is dit belangrijk, motivatie achtergrond, theorie wat is er al bekend?'. Ik heb de feedback met mijn groepsgenoten één voor één verwerkt. We werkten allemaal op de laptop van Jesse, zodat we geen problemen kregen met commiten naar Github. We hebben de grafieken titels en beschrijvingen gegeven. We hebben in de paper vermeld welke versie van R we hebben gebruikt. We hebben ervoor gezorgd dat bij elke tabel een beschrijving erboven staat. Verder hebben we spellingsfouten in de paper verbeterd. Ik heb gecontroleerd of onze repository de juiste structuur heeft. Dit deed ik door op brightspace te kijken bij 'inleverpunt', omdat daar een leidraad te vinden is voor de structuur van onze repository. Ik zag dat de afgeleide data bij 'analyse' moet staan. Onze afgeleide data is het bestand 'cleaned_scores.csv' en die staat bij 'ruwe_data'. Daarom heb het bestand 'cleaned_scores.csv' in 'analyse' gezet. Ik heb deze code in de paper veranderd: data <- read.csv("../ruwe_data/cleaned_scores.csv", header = T, sep = ','). Ik heb hier het woord 'ruwe_data' vervangen door 'analyse', omdat dit bestand nu bij 'analyse' staat en niet bij 'ruwe_data'. Zonder deze aanpassing zouden we foutmeldingen krijgen, omdat de functie read.csv het bestand niet kan vinden. Het bestand zou dan in de verkeerde map staan. Ik heb voor de zekerheid nog even gecontroleerd of alle code nog werkt. De code werkt nog en de repository heeft nu de structuur die we volgens Brightspace moeten aanhouden. Onze paper is klaar. 