---
title: "Protocol | Duitse Taalvaardigheid"
author: "Jesse Postma"
date: "`r Sys.Date()`"
output: html_document
bibliography: protocol_refs.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Onderzoeksprotocol

+-----------------------+---------------------------------------------------------------------+
|                       |                                                                     |
+=======================+=====================================================================+
| Onderzoekers          | Jesse Postma (507655), Vani Rembet (450024), Dennis Kuiper (509448) |
+-----------------------+---------------------------------------------------------------------+
| Instelling            | Hanze Hogeschool Groningen                                          |
+-----------------------+---------------------------------------------------------------------+
| Datum                 | Juni 2026                                                           |
+-----------------------+---------------------------------------------------------------------+
| Versie                | 1.0                                                                 |
+-----------------------+---------------------------------------------------------------------+

## Titel en wetenschappelijke achtergrond

------------------------------------------------------------------------

Titel: Duitse taalvaardigheid onder Nederlandse volwassenen.

De beheersing van het Duits staat in Nederland al geruime tijd onder druk. Tussen 2018 en 2025 daalde het aantal eindexamens Duits met circa 23% (van \~68.000 naar \~49.000). Deze achteruitgrang weerspiegelt zich ook in het hoger onderwijs, waar universitaire Duits-studies te kampen hebben met dalende studentelaantallen. Onderzoek suggereert dat dit deels verklaarbaar is door een curriculum dat zich voornamelijk richt op technische vaardigheden ten koste van taal- en cultuurspecifieke inhoud. [REF?]

Tegelijkertijd blijft Duits economisch en geografisch relevant: Duitsland is de grootste handelspartner van Nederland en de gemeenschappelijke grens van circa 570 km leidt tot dagelijkse interactie in grensregio's. Eerder onderzoek [@Beerkens2010] [@Swarte2013] wijst op een mogelijke receptieve meertaligheid in de grensstreek.

Dit protocol beschrijft de opzet van het surveyonderzoek: van de meetinstrumenten en wervinsstrategie tot de gegevensverwerking en overwegingen.

## Probleemstelling, doelstelling en onderzoeksvragen

------------------------------------------------------------------------

### Probleemstelling

In welke mate beheersen Nederlandse volwassenen de Duitse taal in 2026, en in hoeverre spelen leeftijd, opleidingsniveau en woonlocatie (grensregio versus binnenland) daar een rol in?

### Doelstelling

Inzicht krijgen in de huidige stand van de Duitse taalvaardigheid onder Nederlandse volwassenen, uitgesplits naar leeftijdsgroep, opleidingsniveau en nabijheid van de Duitse grens, met behulp van een gevalideerde taaltoets en achtergrondenquete.

### Hoofdvraag

In hoeverre verschilt de Duitse taalvaardigheid tussen Nederlandse volwassenen van 40 jaar en ouder en jongere volwassenen (18-39 jaar)?

### Deelvragen

- Wat is het gemiddelde CEFR-niveau van Duitse taalvaardigheid per leeftijdsgroep (18-39 jaar en 40+ jaar)?
- Welke rol speelt de woonlocatie (grensstreek vs. binnenland) bij de actieve beheersing van het Duits?
- Heeft het opleidingsniveau invloed op de beheersing van de Duitse taal?
- In welke situaties gebruiken Nederlanders de Duitse taal actief?
- Hoe beoordelen verschillende leeftijdsgroepen het belang van de Duitse taal voor Nederland?

## Hypothesen

------------------------------------------------------------------------

### Primaire hypothese (leeftijd)

- H0: Er is geen significant verschil in het gemiddelde niveau van Duitse taalvaardigheid tussen personen van 40 jaar en ouder en personen jonger dan 40 jaar.
- H1: Personene van 40 jaar en ouder hebben een hoger gemiddeld niveau van Duitse taalvaardigheid dan jongere volwassenen (18-39).

### Secundaire hypothesen

**Locatie** - H0: er is geen veschil in gemiddelde taalbeheersing tussen personen in de grensstreek en personen in het binnenland. - H1: Personen die dichter bij de Duitse grens wonen scoren gemiddeld hoger op de taalvaardigheidtoets.

**Opleidingsniveau** - H0: Er is geen verschil in gemiddelde taalbeheersing tussen personen in de grensstreek en personen in het binnenland. - H1: Een hoger opleidingsniveau gaat samen met een hogere gemiddelde taalvaardigheid Duits.

Verwachte CEFR-niveauverdeling op basis van literatuur: gemiddeld A2 voor jongere groep; gemiddelde B1 voor 40+ groep. Niveaus C1 en C2 worden als zeldzaam beschouwd in de algemene populatie. [ref ERK niveaus]

## Onderzoeksontwerp

------------------------------------------------------------------------

### Type onderzoek

Kwantitatief cross-sectioneel surveyonderzoek. Er wordt éénmalig gemeten; er is geen voor- en nameting. De methode bestaat uit een gecombineerd instrument van een achtergrondenquête en een gestandaardiseerde taaltoets (gebaseerd op CEFR-niveaus A1 t/m C1/2).

### Meetinstrument

Het instrument is samengesteld in Microsoft Forms en bestaat uit die opeenvolgende onderelen: - Deel A: Consentvraag (1 vraag) - Deel B: Achtergrondenquete: persoonskenmerken, blootstelling, gebruik en attitude (11 vragen) - Deel C: Taalvaardigheidstoets Duits: 50 meerkeuzevragen op CEFR-niveau A1 t/m C2

De volledige invultijd bedraagt naar schatting 10-15 minuten. Deelname is volledig anoniem: er worden geen namen, sexes, of e-mailaddressen opgeslagen.

### Taaltoets: opbouw en CEFR-mapping

De taaltoets bestaat uit 50 meerkeuzevragen en beslaat grammaticale en vocabulaire constructies op oplopend niveau. Onderstaande tabel geeft de globale verdeling per CEFR-niveau weer:

Scores worden omgezet naar een CEFR-niveau door middel van drempelwaarden die statistisch worden gebaseerd op de uitslag van de respondenten.

## Enquetevragen

------------------------------------------------------------------------

## Deel A: Toestemming

|     |                                     |                 |        |
|-----|-------------------------------------|-----------------|--------|
| V1  | Wilt u deelnemen aan het onderzoek? | Multiple Choice | Ja/Nee |

Toelichting: Bij "Nee" wordt de deelnemer bedankt en de enquete automatisch geeindigd. Alleen respondenten die "Ja" antwoorden vervolgen het formulier.

## Deel B: Achtergrondenquete

+-----------+--------------------------------------------------------------------------+-----------+----------------------------------------------------+
| Nr.       | Vraag                                                                    | Type      | Opties                                             |
+===========+==========================================================================+===========+====================================================+
| V2        | In welke leeftijdscategorie valt u?                                      | MC        | 18-39 / 40+                                        |
+-----------+--------------------------------------------------------------------------+-----------+----------------------------------------------------+
| V3        | Wat is het hoogste opleidingsniveau waarvoor u bent geslaagd?            | MC        | Basisonderwijs/ VMBO / MBO / HAVO / VWO / HBO / WO |
+-----------+--------------------------------------------------------------------------+-----------+----------------------------------------------------+
| V4        | Hoe ver woont u van de Duitse grens?                                     | Open      | Numeriek getal                                     |
+-----------+--------------------------------------------------------------------------+-----------+----------------------------------------------------+
| V5        | Heeft u ooit in Duitsland gewoond of gewerkt?                            | MC        | Ja/Nee                                             |
+-----------+--------------------------------------------------------------------------+-----------+----------------------------------------------------+
| V6        | Heeft u een Duits familielid of kennis?                                  | MC        | Ja/Nee                                             |
+-----------+--------------------------------------------------------------------------+-----------+----------------------------------------------------+
| V7        | Hoe vaak gebruikt u Duits in het dagelijks leven?                        | MC        | Nooit/Zelden/SOms/Vaak/Dageljks                    |
+-----------+--------------------------------------------------------------------------+-----------+----------------------------------------------------+
| V8        | In welke situaties gebruikt u Duits?                                     | MC        | Werk / Vakantie / Familie / Media / Booschappen    |
+-----------+--------------------------------------------------------------------------+-----------+----------------------------------------------------+
| V9        | Heeft u interesse in het leren van een vreemde taal in het algemeen?     | MC        | Ja/Nee                                             |
+-----------+--------------------------------------------------------------------------+-----------+----------------------------------------------------+
| V10       | Heeft u interesse in het leren van Duits                                 | MC        | Ja/Nee                                             |
+-----------+--------------------------------------------------------------------------+-----------+----------------------------------------------------+
| V11       | Vindt u dat Duits voor Nederlanders een belangrijke taal is om te leren? | MC        | Ja/Nee                                             |
+-----------+--------------------------------------------------------------------------+-----------+----------------------------------------------------+
| V12       | Hoe goed schat u uw eigen Duits in?                                      | Schaal    | 1-5 (Slecht - Vloeiend)                            |
+-----------+--------------------------------------------------------------------------+-----------+----------------------------------------------------+

## Deel C: Taalvaardigheidtoets

Alle toetsvragen zijn meerkeuze (vier opties, een correct antwoord). Hieronder een compleet overzicht:

+----------+-------------+----------------------------------------------------------------------------------------------+
| CEFR     | Question \# | Question                                                                                     |
+==========+=============+==============================================================================================+
| A1       | 13          | ich \_\_\_ gern pizza.                                                                       |
+----------+-------------+----------------------------------------------------------------------------------------------+
| A1       | 14          | \_\_\_ kinder spielen im park.                                                               |
+----------+-------------+----------------------------------------------------------------------------------------------+
| A1       | 15          | die lampe steht \_\_\_ dem tisch.                                                            |
+----------+-------------+----------------------------------------------------------------------------------------------+
| A1       | 16          | ich habe \_\_\_ hund.                                                                        |
+----------+-------------+----------------------------------------------------------------------------------------------+
| A1       | 17          | er \_\_\_ zwei schwestern.                                                                   |
+----------+-------------+----------------------------------------------------------------------------------------------+
| A1       | 18          | das ist \_\_\_ tasche.                                                                       |
+----------+-------------+----------------------------------------------------------------------------------------------+
| A1       | 19          | mein bruder \_\_\_ sehr gut kochen.                                                          |
+----------+-------------+----------------------------------------------------------------------------------------------+
| A1       | 20          | wann \_\_\_ du nach hause?                                                                   |
+----------+-------------+----------------------------------------------------------------------------------------------+
| A1       | 21          | ich trinke \_\_\_ kaffee.                                                                    |
+----------+-------------+----------------------------------------------------------------------------------------------+
| A1       | 22          | wir \_\_\_ gern musik.                                                                       |
+----------+-------------+----------------------------------------------------------------------------------------------+
| A2       | 23          | ich lerne deutsch, \_\_\_ ich in deutschland arbeiten will.                                  |
+----------+-------------+----------------------------------------------------------------------------------------------+
| A2       | 24          | er \_\_\_ gestern nach berlin gefahren.                                                      |
+----------+-------------+----------------------------------------------------------------------------------------------+
| A2       | 25          | ich gebe \_\_\_ frau die blumen.                                                             |
+----------+-------------+----------------------------------------------------------------------------------------------+
| A2       | 26          | das bild hängt \_\_\_ der wand.                                                              |
+----------+-------------+----------------------------------------------------------------------------------------------+
| A2       | 27          | ich gehe in \_\_\_ schule.                                                                   |
+----------+-------------+----------------------------------------------------------------------------------------------+
| A2       | 28          | ich freue \_\_\_ auf den urlaub.                                                             |
+----------+-------------+----------------------------------------------------------------------------------------------+
| A2       | 29          | ich habe \_\_\_ neuen computer gekauft.                                                      |
+----------+-------------+----------------------------------------------------------------------------------------------+
| A2       | 30          | welke zin is juist?                                                                          |
+----------+-------------+----------------------------------------------------------------------------------------------+
| A2       | 31          | \_\_\_ sie bitte langsamer!                                                                  |
+----------+-------------+----------------------------------------------------------------------------------------------+
| A2       | 32          | das kind hat sich \_\_\_ erkältet.                                                           |
+----------+-------------+----------------------------------------------------------------------------------------------+
| B1       | 33          | welcher satz verwendet den relativsatz richtig?                                              |
+----------+-------------+----------------------------------------------------------------------------------------------+
| B1       | 34          | wenn ich reich \_\_\_, würde ich um die welt reisen.                                         |
+----------+-------------+----------------------------------------------------------------------------------------------+
| B1       | 35          | das ist die frau, \_\_\_ ich gestern geholfen habe.                                          |
+----------+-------------+----------------------------------------------------------------------------------------------+
| B1       | 36          | ich helfe \_\_\_ kollegin gern.                                                              |
+----------+-------------+----------------------------------------------------------------------------------------------+
| B1       | 37          | welke zin is grammaticaal correct?                                                           |
+----------+-------------+----------------------------------------------------------------------------------------------+
| B1       | 38          | es ist wichtig, viel wasser \_\_\_ trinken.                                                  |
+----------+-------------+----------------------------------------------------------------------------------------------+
| B1       | 39          | welke zin is grammaticaal correct?2                                                          |
+----------+-------------+----------------------------------------------------------------------------------------------+
| B1       | 40          | welke zin drukt een (onrealistische) wens uit?                                               |
+----------+-------------+----------------------------------------------------------------------------------------------+
| B1       | 41          | ich werde dich morgen \_\_\_.                                                                |
+----------+-------------+----------------------------------------------------------------------------------------------+
| B1       | 42          | welke zin is correct?                                                                        |
+----------+-------------+----------------------------------------------------------------------------------------------+
| B2       | 43          | in welke zin is het duitse deelwoord grammaticaal correct gebruikt?                          |
+----------+-------------+----------------------------------------------------------------------------------------------+
| B2       | 44          | welke zin is stylistisch en grammaticaal correct?                                            |
+----------+-------------+----------------------------------------------------------------------------------------------+
| B2       | 45          | die \_\_\_ der ergebnisse dauert noch an.                                                    |
+----------+-------------+----------------------------------------------------------------------------------------------+
| B2       | 46          | welke zin is grammaticaal correct?3                                                          |
+----------+-------------+----------------------------------------------------------------------------------------------+
| B2       | 47          | er behauptet, er \_\_\_ nichts davon gewusst.                                                |
+----------+-------------+----------------------------------------------------------------------------------------------+
| B2       | 48          | welke zin is correct?                                                                        |
+----------+-------------+----------------------------------------------------------------------------------------------+
| B2       | 49          | welke zin drukt een vermoeden over het verleden uit?                                         |
+----------+-------------+----------------------------------------------------------------------------------------------+
| B2       | 50          | in welke zin is een werkwoord correct als zelfstandig naamwoord gebruikt?                    |
+----------+-------------+----------------------------------------------------------------------------------------------+
| B2       | 51          | welke zin is grammaticaal correct?4                                                          |
+----------+-------------+----------------------------------------------------------------------------------------------+
| B2       | 52          | die frage \_\_\_ noch einer klärung.                                                         |
+----------+-------------+----------------------------------------------------------------------------------------------+
| C1/2     | 53          | die entscheidung \_\_\_ auf heftigen widerstand.                                             |
+----------+-------------+----------------------------------------------------------------------------------------------+
| C1/2     | 54          | welke zin gebruikt de duitse 'gevoelswoordjes' (zoals 'halt' of 'eben') op de juiste manier? |
+----------+-------------+----------------------------------------------------------------------------------------------+
| C1/2     | 55          | welke zin is stylistisch en grammaticaal correct?2                                           |
+----------+-------------+----------------------------------------------------------------------------------------------+
| C1/2     | 56          | welke zin drukt een tegenstelling (met 'hoewel') grammaticaal correct uit?                   |
+----------+-------------+----------------------------------------------------------------------------------------------+
| C1/2     | 57          | in welke zin wordt de uitspraak van de minister op de grammaticaal juiste manier naverteld?  |
+----------+-------------+----------------------------------------------------------------------------------------------+
| C1/2     | 58          | welke zin is grammaticaal correct?5                                                          |
+----------+-------------+----------------------------------------------------------------------------------------------+
| C1/2     | 59          | die studie lässt \_\_\_ schließen, dass weitere forschung nötig ist.                         |
+----------+-------------+----------------------------------------------------------------------------------------------+
| C1/2     | 60          | welke zin bevat de juiste bijzin?                                                            |
+----------+-------------+----------------------------------------------------------------------------------------------+
| C1/2     | 61          | der bericht, \_\_\_ ergebnisse kontrovers diskutiert wurden, liegt nun vor.                  |
+----------+-------------+----------------------------------------------------------------------------------------------+
| C1/2     | 62          | es \_\_\_ noch zu klären, inwieweit diese regelung anwendbar ist.                            |
+----------+-------------+----------------------------------------------------------------------------------------------+

## Doelgroep, inclusie- en exclusiecriteria

------------------------------------------------------------------------

### Doelgroep

Nederlandse volwassenen van 18 jaar en ouder, zonder Duits als moedertaal, die tenminste tien jaar in Nederland wonen en het Nederlands voldoende beheersen om een enquete te begrijpen.

### Inclusiecriteria

- Leeftijd 18 jaar of ouder
- Woont minimaal 10 jaar in Nederland
- Duits is niet een moedertaal
- Voldoende Nederlands om de vragenlijst in te vullen
- Bereid tot deelname na mondelinge toestemming

### Exclusiecriteria

- Leeftijd jonger dan 18 jaar
- Duits als moedertaal (e.g. Duitse studenten/expats in Nederland)
- Minder dan 10 jaar wonend in Nederland
- Onvoldoende begrip Nederlandse taal
- Geen consent voor de vragenlijst

### Steekproefomvang en -methode

Nagestreefde minimale steekproef: 40 respondenten. Uiteindelijk gerealiseerd: 154 respondenten, weergegeven in de dataset(s) in '/ruwe_data'.

Steekproefmethode: gelegenheidssteekproef, aangevuld door werving via persoonlijk netwerk. Gekozen gezien gemakkelijke wegen van connectie via bijvoorbeeld social media. Daarnaast waren er flyers beschikbaar voor gemakkelijke toegang tot de vragenlijst in een openbare ruimte.

## Wervingsstrategie

------------------------------------------------------------------------

## Kanalen

Respondenten werden via de volgende kanalen geworven:

+---------------------+--------------------------------------------------------------+------------------------------------------------------------------+
| Kanaal              | Methode                                                      | Opmerkingen                                                      |
+=====================+==============================================================+==================================================================+
| Openbare ruimtes    | Benadering met QR-code (poster).                             | Werk, cafe's                                                     |
+---------------------+--------------------------------------------------------------+------------------------------------------------------------------+
| Sociaal netwerk     | WhatsApp, mondelinge verzoeken aan vrienden/familie/kenissen | Meeste respondenten afkomstig uit sociaal netwerk                |
+---------------------+--------------------------------------------------------------+------------------------------------------------------------------+
| Facebook, Instagram | Posts met aanroepen tot invullen                             | Gerichte posts in enquetegroepen/ 40+ groepen ook van toepassing |
+---------------------+--------------------------------------------------------------+------------------------------------------------------------------+
| SurveyCircle        | "Last measure"                                               | 0 respondenten geworven                                          |
+---------------------+--------------------------------------------------------------+------------------------------------------------------------------+

### Mondelinge wervingsscript

Bij persoonlijke benadering in openbare ruimtes werd het volgende script gehanteerd:

**Stap 1 - opening:**

"Hallo, wij doen voor onze studie een onderzoek naar hoe goed Nederlanders nog Duits kunnen. Zou u ons willen helpen? Het duurt ongeveer x minuten."

**Stap 2 - Screening taal:**

"Is Duits uw moedertaal?" - Ja -\> "Dan valt u buiten onze doelgroep. Bedankt voor uw tijd." - Nee -\> voortzetting stap 3

**Stap 3 - Screening woonsituatie:**

"Hoe lang woont u al in Nederland?" - antwoord \> 10 -\> voortzetting stap 4 - antwoord \< 10 jaar -\> "Dan valt u buiten onze doelgroep. Bedankt voor uw tijd."

**Stap 4 - Screening leeftijd:**

"Mag ik vragen hoe oud u bent?" - antwoord \> 18 -\> voortzetting stap 5 - antwoord \< 18 jaar -\> "Dan valt u buiten onze doelgroep. Bedankt voor uw tijd."

**Stap 5 - Doelinformatie en overhandiging survey:**

"Wij onderzoeken het verschil in taalbeheersing van verschillende generaties. Dit doen wij voor een onderzoek bij de Hanze Hogeschool Groningen. De enquête is volledig anoniem. Wilt u meedoen?‟ - Ja -\> QR-code tonen of toegang tot survey verlenen via ander medium. - Nee -\> "Geen probleem, fijne dag!"

## Uitvoeringsprocedure

------------------------------------------------------------------------

### Materialen

- Microsoft Forms-formulier (online)
- A5-poster met duidelijke QR-code en korte insructie.
- Eigen smartapparaat als back-up voor respondenten zonder smartphone.
- Programmeertaal R voor statistische verwerking en visualisatie

### Gegevensverzameling

Elke respondent doorloopt het formulier in drie onderdelen:

1.  Toestemmingsvraag
2.  Achtergrondenquete
3.  Taaltoets

Alle antwoorden worden automatisch opgeslagen in Microsoft Forms en zijn exporteerbaar als .xlsx. De dataset is geconverteerd naar een .csv bestand voor analyse in R.

### Tijdspad

+---------------+-----------------------+-----------------------------------------------------------+
| Week          | Periode               | Activiteit                                                |
+===============+=======================+===========================================================+
| 1             | 20-26 april 2026      | Onderwerpsselectie en literatuurverkenning.               |
+---------------+-----------------------+-----------------------------------------------------------+
| 2             | 27 april - 3 mei 2026 | Docentsfeedback; opstelling PvA                           |
+---------------+-----------------------+-----------------------------------------------------------+
| 3             | 4-10 mei 2026         | Bouwen Forms, drukken posters, start werving              |
+---------------+-----------------------+-----------------------------------------------------------+
| 4             | 11-17 mei             | Dataverzameling                                           |
+---------------+-----------------------+-----------------------------------------------------------+
| 5             | 18-24 mei             | Data-export, opschonen data, beginnen exploratie binnen R |
+---------------+-----------------------+-----------------------------------------------------------+
| 6             | 25-31 mei             | Statistische analyses en visualisaties in R               |
+---------------+-----------------------+-----------------------------------------------------------+
| 7             | 1-7 juni              | Schrijven paper, verdere analyse en inhoud                |
+---------------+-----------------------+-----------------------------------------------------------+
| 8             | 7-9 juni              | Eindcorrectie en inlevering                               |
+---------------+-----------------------+-----------------------------------------------------------+

## Ethische overwegingen

------------------------------------------------------------------------

### Anonimiteit en informed consent

Deelname aan het onderzoek is volledig anoniem. Er worden geen persoonsidentificerende gegevens opgeslagen (geen naam, geen e-mailadres, geen IP-adres). De eerste vraag van het formulier is een expliciete toestemmingsvraag; respondenten die “Nee” antwoorden worden direct doorgestuurd naar een bedankpagina en hun (lege) respons wordt niet opgeslagen.

### Kwetsbare groepen

Er is geen doelgerichte werving onder kwetsbare groepen. Minderjarigen (jonger dan 18 jaar) worden als inclusievraag uitgesloten. Bij benadering in openbare ruimtes werden potentiële respondenten die tekenen van cognitieve beperkingen vertoonden niet actief benaderd.

### Dataveiligheid

De ruwe data worden opgeslagen op een GitHub-repository. Toegang is openbaar, al is de data volledig geanonimiseerd. Bij publicatie of inlevering wordt de dataset korte tijd bewaard conform de richtlijnen voor studentenonderzoek aan de Hanze Hogeschool Groningen.

## Risicoanalyse

------------------------------------------------------------------------

+------------------------------------------------------------------+------------------------------------------------------+----------------------------------------------------------------------------+
| Risico                                                           | Impact                                               | Mitigatie                                                                  |
+==================================================================+======================================================+============================================================================+
| Respondenten buiten doelgroep (toeristen, expats, minderjarigen) | Vertekening resultaten                               | Screening op basis van leeftijd, moedertaal, verblijfsduur.                |
+------------------------------------------------------------------+------------------------------------------------------+----------------------------------------------------------------------------+
| Selectiebias:                                                    | Beperkte externe validiteit, geografische clustering | Actieve werving in openbare ruimtes en via netwerken als Facebook.         |
|                                                                  |                                                      |                                                                            |
| oververtegenwoordiging sociale kring                             |                                                      |                                                                            |
+------------------------------------------------------------------+------------------------------------------------------+----------------------------------------------------------------------------+
| Lage respons oudere groepen                                      | Oneven verdeling leeftijdsgropen                     | Gerichte benadering                                                        |
+------------------------------------------------------------------+------------------------------------------------------+----------------------------------------------------------------------------+
| Begripsproblemen toetsvragen                                     | Meting van begrijpend lezen ipv taalvaardigheid      | Korte instructieteksten, simpele uitleg, meerkeuze format.                 |
+------------------------------------------------------------------+------------------------------------------------------+----------------------------------------------------------------------------+
| Onnauwkeurige inschatting                                        | Wenselijkheidbias                                    | Vergelijken schatting vs werkelijke score                                  |
+------------------------------------------------------------------+------------------------------------------------------+----------------------------------------------------------------------------+
| Surveycircle (0 respondents)                                     | Geen impact; kanaal niet representatief              | \-                                                                         |
+------------------------------------------------------------------+------------------------------------------------------+----------------------------------------------------------------------------+
| Onvolledige invulling                                            | Gemiste/onvolledige data                             | Pauzeren forms mogelijk, lokken met zien uiteindelijke score op het einde. |
+------------------------------------------------------------------+------------------------------------------------------+----------------------------------------------------------------------------+

## Gegevensverwerking en statistische analyse

------------------------------------------------------------------------

### Datastructuur

De dataset wordt geexporteerd vanuit Microsoft Forms als .xlsx en omgezet naar .csv. Elke rij representeert een respondent (n = 154). Kolommen zijn onderverdeeld in: - Administratieve kolommen (ID, tijdstempels, Forms-metadata)\
- Responskolommen achtergrond - Responskolommen taaltoets

### Geplande analyses in R

- Beschrijven resultaten
- Hypothese testen
- Exploratie andere data

### Statistische Methoden

• Beschrijvende statistiek: gemiddelden, medianen, standaarddeviaties per groep • Groepsvergelijking: onafhankelijke t-toets (twee leeftijdsgroepen) of Mann-Whitney U (bij niet-normale verdeling) • Correlatie: Spearmans rangcorrelatie tussen afstand tot de grens en toetsscore • Variantieanalyse: ANOVA of Kruskal-Wallis voor vergelijking drie of meer opleidingsniveaus

## Fair-principes en management

### Findable

•	Dataset heeft een beschrijvende bestandsnaam: resultaat.xlsx / resultaat.csv
•	Een README-bestand beschrijft de inhoud van elke kolom
•	Mappenstructuur: /ruwe_data, /analyse, /figures, /scripts

### Accessible

•	Opgeslagen op Hanze OneDrive (toegankelijk voor onderzoekers en begeleiders)
•	Geback-upt in privé GitHub-repository
•	Bestanden te openen in Excel, R en LibreOffice Calc zonder speciale software

### Interoperable

•	Export als open formaat (.csv) voor gebruik in R
•	Kolomnamen zijn beschrijvend en gestandaardiseerd
•	Aandachtspunt: één cel bevat meerdere waarden (V8: meervoudig mc) — vereist opschoning in R (one-hot encoding).

### Reusable

•	Dataverzamelingsprotocol (dit document) beschrijft alle stappen volledig
•	Inclusie- en exclusiecriteria zijn gedocumenteerd
•	Hergebruik door een externe onderzoeker is mogelijk mits toegang tot de README

## Verzamelde literatuur

Abitzsch, D., Knopp, E., & Michel, M. (2024). Motivatie om Duits te studeren aan Nederlandse universiteiten. Levende Talen Tijdschrift, (2), 13–24.
Beeker, A., Fasoglio, D., de Jong, K., Keuning, J., & van Til, A. (2015). Weergave van ERK-niveau schrijfvaardigheid Engels, Duits en Frans. Levende Talen Tijdschrift, (2), 16–25.
Beerkens, R. (2010). Receptive multilingualism as a language mode in the Dutch-German border area. Waxmann Publishing Co.
Gille, E., & Kordes, J. (2013). Weergave van vaardigheid Engels en Duits van Nederlandse leerlingen in Europees perspectief. Levende Talen Magazine, (1), 23–27.
Swarte, F., Schüppert, A., & Gooskens, C. (2013). Do speakers of Dutch use their knowledge of German while processing written Danish words? Linguistics in the Netherlands, 30(1), 146–159.
Van den Noort, M. W. M. L., Bosch, P., & Hugdahl, K. (2006). Foreign language proficiency and working memory capacity. European Psychologist, 11(4), 289–296.
Verkuil, D. (2015, maart). Hoge prijs voor gebrekkig Duits. NOS. https://nos.nl/artikel/2026034
Weltens, B., de Bot, K., & van Els, T. (1986). Language attrition in progress. Floris Publications.
Wilhelm, F. (2018). Foreign language teaching and learning in the Netherlands 1500–2000. The Language Learning Journal, 46(1), 17–27.
Zinecker, M., & Konečná, Z. (2014). German language proficiency among students of business and management in the Czech Republic. DANUBE: Law and Economics Review, 5(3), 173–200.

## Referenties
